INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ABINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ACTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ACUSHNET',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ADAMS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AGAWAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ALFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AMESBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AMHERST',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ANDOVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AQUINNAH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ARLINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ASHBURNHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ASHBY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ASHFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ASHLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ATHOL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ATTLEBORO',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AUBURN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AVON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('AYER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BARNSTABLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BARRE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BECKET',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BEDFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BELCHERTOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BELLINGHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BELMONT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BERKLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BERLIN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BERNARDSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BEVERLY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BILLERICA',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BLACKSTONE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BLANDFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BOLTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BOSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BOURNE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BOXBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BOXFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BOYLSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BRAINTREE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BREWSTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BRIDGEWATER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BRIMFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BROCKTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BROOKLINE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BUCKLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('BURLINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CAMBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CANTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CARLISLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CARVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHARLEMONT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHARLTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHATHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHELMSFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHELSEA',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHESHIRE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHESTERFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHICOPEE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CHILMARK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CLARKSBURG',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CLINTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('COHASSET',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('COLRAIN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CONCORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CONWAY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('CUMMINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DALTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DANVERS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DARTMOUTH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DEDHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DEERFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DENNIS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DIGHTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DOUGLAS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DOVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DRACUT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DUDLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DUNSTABLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('DUXBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('E. BRIDGEWATER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('E. BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('E. LONGMEADOW',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EAST BRIDGEWATER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EAST BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EAST LONGMEADOW',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EASTHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EASTHAMPTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EASTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EDGARTOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EGREMONT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ERVING',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ESSEX',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('EVERETT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FAIRHAVEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FALL RIVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FALMOUTH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FITCHBURG',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FLORIDA',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FOXBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FRAMINGHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FRANKLIN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('FREETOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GARDNER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GEORGETOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GILL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GLOUCESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GOSHEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GOSNOLD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GRAFTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GRANBY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GRANVILLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GREAT BARRINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GREENFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GROTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('GROVELAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HADLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HALIFAX',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HAMILTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HAMPDEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HANCOCK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HANOVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HANSON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HARDWICK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HARVARD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HARWICH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HATFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HAVERHILL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HAWLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HEATH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HINGHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HINSDALE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOLBROOK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOLDEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOLLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOLLISTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOLYOKE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOPEDALE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HOPKINTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HUBBARDSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HUDSON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HULL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('HUNTINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('IPSWICH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('KINGSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LAKEVILLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LANCASTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LANESBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LAWRENCE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LEE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LEICESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LENOX',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LEOMINSTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LEVERETT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LEXINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LEYDEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LINCOLN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LITTLETON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LONGMEADOW',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LOWELL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LUDLOW',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LUNENBURG',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LYNN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('LYNNFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MALDEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MANCHESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MANSFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MARBLEHEAD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MARION',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MARLBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MARSHFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MASHPEE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MATTAPOISETT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MAYNARD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MEDFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MEDFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MEDWAY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MELROSE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MENDON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MERRIMAC',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('METHUEN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MIDDLEBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MIDDLEFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MIDDLETON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MILFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MILLBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MILLIS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MILLVILLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MILTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MONROE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MONSON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MONTAGUE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MONTEREY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MONTGOMERY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('MOUNT WASHINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('N. ADAMS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('N. ANDOVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('N. ATTLEBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('N. BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('N. READING',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NAHANT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NANTUCKET',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NATICK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEEDHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEW ASHFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEW BEDFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEW BRAINTREE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEW MARLBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEW SALEM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEWBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEWBURYPORT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NEWTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORFOLK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTH ADAMS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTH ANDOVER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTH ATTLEBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTH BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTH READING',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTHAMPTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTHBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTHBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTHFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORWELL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('NORWOOD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('OAK BLUFFS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('OAKHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ORANGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ORLEANS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('OTIS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('OXFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PALMER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PAXTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PEABODY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PELHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PEMBROKE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PEPPERELL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PERU',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PETERSHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PHILLIPSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PITTSFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PLAINFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PLAINVILLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PLYMOUTH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PLYMPTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PRINCETON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('PROVINCETOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('QUINCY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('RANDOLF',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('RANDOLPH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('RAYNHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('READING',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('REHOBOTH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('REVERE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('RICHMOND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ROCHESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ROCKLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ROCKPORT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ROWE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ROWLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('ROYALSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('RUSSELL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('RUTLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('S. HADLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SALEM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SALISBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SANDISFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SANDWICH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SAUGUS',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SAVOY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SCITUATE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SEEKONK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHARON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHEFFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHELBURNE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHERBORN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHIRLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHREWSBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SHUTESBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOMERSET',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOMERVILLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOUTH HADLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOUTHAMPTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOUTHBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOUTHBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SOUTHWICK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SPENCER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SPRINGFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('STERLING',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('STOCKBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('STONEHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('STOUGHTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('STOW',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('STURBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SUDBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SUNDERLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SUTTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SWAMPSCOTT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('SWANSEA',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TAUNTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TEMPLETON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TEWKSBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TISBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TOLLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TOPSFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TOWNSEND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TRURO',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TYNGSBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('TYRINGHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('UPTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('UXBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. BOYLSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. BRIDGEWATER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. NEWBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. SPRINGFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. STOCKBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('W. TISBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WAKEFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WALES',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WALPOLE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WALTHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WARE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WAREHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WARREN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WARWICK',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WASHINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WATERTOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WAYLAND',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEBSTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WELLESLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WELLFLEET',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WENDELL',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WENHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST BOYLSTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST BRIDGEWATER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST BROOKFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST NEWBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST SPRINGFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST STOCKBRIDGE',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEST TISBURY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTBOROUGH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTFIELD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTFORD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTHAMPTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTMINSTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTPORT',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WESTWOOD',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WEYMOUTH',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WHATELY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WHATLEY',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WHITMAN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WILBRAHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WILLIAMSBURG',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WILLIAMSTOWN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WILMINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WINCHENDON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WINCHESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WINDSOR',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WINTHROP',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WOBURN',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WORCESTER',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WORTHINGTON',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('WRENTHAM',1,1,date('now'),date('now'));
INSERT INTO municipalities(name, created_by,modified_by,created_on,modified_on) VALUES ('YARMOUTH',1,1,date('now'),date('now'));
